model:
    ##################################################
    # Pre-trained transfer model (typically rodent)
    #
    # Path
    pre_trained_model_path: ""
    #
    # Filename of .h5 file (if empty string no pre-training will be done)
    # pre_trained_model_file_name: "Liver_ballooning_model_V1.06.h5"
    pre_trained_model_file_name: ""

    ##################################################
    # Resulting model
    #
    # Path
    model_path: "./model/"
    #
    # Filename of resulting model
    model_file_name: "HS_Liver_ballooning_model_IN_V0.41_test.h5"

tiles:
    # Path where the tiles with the ground truth are located in a folder ./train
    ground_truth_path: "./CNN/fibrosis/"
    
settings:
    # Max number of epochs to train
    max_epochs: 30

    # Generate a confusion matrix and save it
    generate_confusion_matrix: True

    # Automatically split train and validation data
    do_val_split: False
    val_fraction: 0.05
